apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book
  ports:
    - protocol: TCP
      port: 8080  # Exposed port on the Service
      targetPort: 8080  # Port inside the container (Tomcat)
  type: LoadBalancer  # External acces
